### ISSUE TITLE
Roadmap for 2.0

### ISSUE THREAD

**Issue by satya164** [callstack/react-native-paper#350]
This issue is to collect breaking changes in the next major release:

- [ ] Consistent handling of margins #334
- [ ] Improved Portals #43 
- [ ] Proper RTL support
- [x] Remove support for React elements for `icon` prop (superseded by render callback)
- [x] Remove `SearchBar` export (renamed to `Searchbar`)

Changes live at: https://github.com/callstack/react-native-paper/tree/material-next

**Comment by necolas** [comment]
Does this officially support web via react-native-web yet?

**Comment by satya164** [comment]
@necolas we haven't tested on react-native-web, but I've seen someone using it with react-native-web. it should work more or less since we don't use any native stuff.

**Comment by necolas** [comment]
Might be worth adding it to your roadmap. I can help figure out any web-specific issues you come across

**Comment by ferrannp** [comment]
We use 2.0.0 milestone.
